<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>

  <ItemGroup>
	  
    <!-- ASP.NET Core / shared -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
	  
  </ItemGroup>
</Project>
